version: '3.3'

services:
  postgres:
    image: postgres:13
    # build: database/
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    # environment:
    #  - PGADMIN_DEFAULT_EMAIL=root@admin.com
    #  - PGADMIN_DEFAULT_PASSWORD=root
    env_file:
      - db.env
    depends_on:
      - postgres